### ISSUE TITLE
Nicknames extension

### ISSUE THREAD

**Issue by mjf** [cloudflare/saffron#12]
I propose to support "nicknames" extension and provide at least the following (as listed in `crontab(5)` in most *unices*):

```groff
.SH EXTENSIONS
These special time specification "nicknames" which replace the 5 initial
time and date fields, and are prefixed with the '@' character, are
supported:
.PP
.nf
@reboot    :    Run once after reboot.
@yearly    :    Run once a year, ie.  "0 0 1 1 *".
@annually  :    Run once a year, ie.  "0 0 1 1 *".
@monthly   :    Run once a month, ie. "0 0 1 * *".
@weekly    :    Run once a week, ie.  "0 0 * * 0".
@daily     :    Run once a day, ie.   "0 0 * * *".
@hourly    :    Run once an hour, ie. "0 * * * *".
.fi
```

These "nicknames" may be very handy for *Cloudflare* **users** for they are easy to comprehend, I think (of course, without the `@reboot` one if you do not find some special use for it too which I have no way to find out).

I would also suggest to provide `@midnight` as an alias for `@daily` for ease of use and completeness if you ever managed to support the "nicknames" extension I propose.

-----

As an adition it would be quite useful if a **developer** using the crate could even add custom "nicknames" (i.e. `@noon`) somehow easily - without forking it and extending the parser etc.

**Comment by ObsidianMinor** [comment]
Nicknames are a pretty easy case to handle in most languages outside of the parser since it doesn't have any conflicting characters that identify it, it's just a '@' prefix. So this could be handled as a pre-parse step instead of an explicit part of parsing in this library.

For example, in Rust:
```rust
let value = "@hourly";
let cron: Cron = value.strip_prefix('@').map(|nickname| match nickname {
    "yearly" | "annually" => "0 0 1 1 *",
    "monthly" => "0 0 1 * *",
    "weekly" => "0 0 * * 1",
    "daily" => "0 0 * * *",
    "hourly" => "0 * * * *",
    _ => panic!("Unknown nickname"),
}).unwrap_or(cron).parse().expect("Valid cron");
```

In JavaScript:
```js
let value = "@hourly";
if (value.startsWith("@")) {
    switch (value.substr(1)) {
        case "yearly":
        case "annually":
            value = "0 0 1 1 *";
            break;
        // etc, etc
        default:
            throw new Error("Unknown nickname");
    }
}
let cron = new Cron(value);
```

Or Go:
```go
value := "@hourly"
if strings.HasPrefix(value, "@") {
    switch nickname := strings[1:]; nickname {
    case "yearly":
    case "annually":
        value = "0 0 1 1 *"
    default:
         return errors.New("Unknown nickname")
    }
}
cron, err := saffron.Parse(value)
```

Keeping a translation step outside the library like this would ultimately be easier to develop for across languages and give developers the most control should they use this library in any of its bindings.

**Comment by mjf** [comment]
@ObsidianMinor Thank you. You can close the issue, I guess, now.
